//
//  ChatMessage.swift
//  QuizEngineCore
//
//  Created by Matt on 28/10/2025.
//

import Foundation

public struct ChatMessage: Identifiable, Equatable {
    public enum Role: Equatable {
        /// A message coming from the user.
        case user
        /// A response generated by the assistant.
        case assistant
    }

    public let id: UUID
    public let role: Role
    public let text: String
    public let imageURL: URL?

    public init(id: UUID = UUID(), role: Role, text: String, imageURL: URL? = nil) {
        self.id = id
        self.role = role
        self.text = text
        self.imageURL = imageURL
    }
}
